# fly.toml app configuration file generated for qr-code on 2023-09-19T09:54:20-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "qr-code"
primary_region = "gdl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
